### ISSUE TITLE
Feature-Request: Duplicate Groups

### ISSUE THREAD

**Issue by ghost** [Sponk/NeoEditor#150] opened 2015-01-08 07:52 UTC
Right now I have a slightly larger problem with the duplicate of groups.

A small example:
I have created a non-player character. This non-player character is now, along with all the hit boxes and stuff in a group. I would like to duplicate this group, but only the empty group is always duplicated. All child-elements of the original group are ignored and not duplicated together, so I have to re-sort manually all the child-elements into the group.

Perhaps there is also a workaround, I do not know yet? :-)

**Comment by Sponk** [comment] 2015-01-08 11:23
You can duplicate your current selection, even if you selected multiple objects. As a workaround: Try to select all objects and then duplicate them.

Groups need some work in the editor, that's true. I'll look into that.

**Comment by Akira1San** [comment] 2015-01-08 17:06
Maybe add the objects into a prefab.

**Comment by jamesgeek** [comment] 2015-01-09 08:11
Thank you for your help suggestions!

1. Select multiple objects only works directly in the 3D view. Especially with overlapping objects (such as the hit boxes) is the selection very tricky :-D Unfortunately, there is on the left side (in the case of a multiple selection) no visual feedback, what you really selected. In this context, I also noticed that the numbers at the end of the object name are not counted correctly. The duplicate of an object with the name "Entity1" has, for example, then the name "Entity11". If you then subsequently adjusts the names and accidentally caught an already existing name ... Suddenly ... The object disappears on the left side, but is in the 3D view still under the same name selectable. I'm not sure if this is a bug or a feature :-)

2. Prefabs works almost perfectly in this case. Unfortunately, when loading a Prefab all object names are ignored, so I have to rename all the objects back again. The correct wording is essential, especially for larger projects. Imagine just a great forest with very different vegetation. If every tree, bush and stone would be called "Entity123" (and so on...) I think I'd go crazy :-D

**Comment by Akira1San** [comment] 2015-01-09 16:06
Yes, thats important workflow that need to be fixed.

**Comment by Sponk** [comment] 2015-01-10 09:55
I will first work on getting multi select of objects in the list view working and then I'll look into how that naming stuff works.

**Comment by jamesgeek** [comment] 2015-01-12 07:14
Thanks for the multiple selection in the list view! It works great! :-)

**Comment by Sponk** [comment] 2015-03-15 20:29
I implemented the duplication of children, i.e. copying groups is now working.
Furthermore I implemented a method to prevent those ugly names from happening, i.e. names like "Entity1111111" are no longer possible when copying objects.

Closing

**Closed by Sponk** 2015-03-15 20:29 UTC
Labels: editor, enhancement
